"""
SaaS Dashboard Report Template
Professional enterprise-grade theme: Dark mode, orange accent, Poppins font
Includes working JS for all interactive features, export functionality, and print support.
"""

import html as html_module
import json


def build_saas_report(logo_base64, report_date, stats, ciso_data, risk_sections, charts_data, developer_info):
    """
    Build complete SaaS-style HTML report.
    Returns full HTML string.
    """
    logo_img = f'<img src="{logo_base64}" alt="Logo" class="header-logo" />' if logo_base64 else '<i data-lucide="shield" class="header-logo-icon"></i>'
    kpis = ciso_data.get('kpis', {})

    # Overview cards from CISO KPIs
    overview_cards = _build_overview_cards(kpis)

    # Sidebar nav items
    nav_items = _build_nav_items(stats)

    # Tab content wrapped for Bootstrap
    tab_content = f'<div class="tab-content" id="pills-tabContent">{risk_sections}</div>'

    charts_json = json.dumps(charts_data, default=str)
    ciso_charts = json.dumps({
        'risk_distribution': {'labels': list(ciso_data.get('risk_distribution', {}).keys()), 'data': list(ciso_data.get('risk_distribution', {}).values())},
        'risk_categories': {'labels': list(ciso_data.get('risk_by_category', {}).keys()), 'data': list(ciso_data.get('risk_by_category', {}).values())}
    }, default=str)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AtilKurt - Active Directory Security Report</title>
    <meta name="description" content="Enterprise Active Directory Security Health Check Report generated by AtilKurt">
    <!-- Offline-first: local vendor assets (vendor/ folder must sit next to this HTML file) -->
    <link href="vendor/bootstrap.min.css" rel="stylesheet">
    <link href="vendor/fontawesome.min.css" rel="stylesheet">
    <script src="vendor/bootstrap.bundle.min.js"></script>
    <script src="vendor/chart.umd.min.js"></script>
    <script>
        if (typeof Chart !== 'undefined') {{
            Chart.defaults.color = '#94a3b8';
            Chart.defaults.borderColor = 'rgba(255, 107, 0, 0.3)';
            Chart.defaults.backgroundColor = ['#ff6b00', '#ff8533', '#ff9f66', '#e55a00', '#cc4d00'];
            Chart.defaults.plugins.legend.labels.color = '#94a3b8';
            Chart.defaults.scale.grid.color = 'rgba(148, 163, 184, 0.1)';
            Chart.defaults.scale.ticks.color = '#94a3b8';
        }}
    </script>
    <script src="vendor/lucide.min.js"></script>
    <style>
        /* ═══════════════════════════════════════════════════════════════
           DESIGN SYSTEM - CSS Custom Properties
           ═══════════════════════════════════════════════════════════════ */
        :root {{
            --accent: #ff6b00;
            --accent-hover: #ff8533;
            --accent-light: rgba(255, 107, 0, 0.15);
            --accent-glow: rgba(255, 107, 0, 0.4);
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --bg-card: #161b22;
            --bg-sidebar: rgba(13, 17, 23, 0.97);
            --text-primary: #f0f6fc;
            --text-secondary: #8b949e;
            --text-muted: #6e7681;
            --border-color: rgba(255, 107, 0, 0.2);
            --border-subtle: rgba(255, 255, 255, 0.06);
            --risk-critical: #ef4444;
            --risk-high: #ff6b00;
            --risk-medium: #eab308;
            --risk-low: #22c55e;
            --success-color: #22c55e;
            --warning-color: #eab308;
            --danger-color: #ef4444;
            --sidebar-width: 260px;
            --header-height: 64px;
            --header-bg: #161b22;
        }}

        /* ═══════════════════════════════════════════════════════════════
           BASE & RESET
           ═══════════════════════════════════════════════════════════════ */
        *, *::before, *::after {{ box-sizing: border-box; }}
        html {{ scroll-behavior: smooth; }}
        body {{
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
            background: var(--bg-primary) !important;
            color: var(--text-primary) !important;
            margin: 0; padding: 0;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }}
        ::selection {{ background: var(--accent); color: #fff; }}

        /* ═══════════════════════════════════════════════════════════════
           SKIP LINK (Accessibility)
           ═══════════════════════════════════════════════════════════════ */
        .skip-link {{
            position: absolute; top: -100px; left: 16px;
            background: var(--accent); color: #fff;
            padding: 8px 16px; border-radius: 8px; z-index: 9999;
            text-decoration: none; font-weight: 600;
            transition: top 0.2s ease;
        }}
        .skip-link:focus {{ top: 16px; }}

        /* ═══════════════════════════════════════════════════════════════
           HEADER
           ═══════════════════════════════════════════════════════════════ */
        .app-header {{
            position: sticky; top: 0; z-index: 1030;
            display: flex; align-items: center; justify-content: space-between;
            height: var(--header-height); padding: 0 24px;
            background: var(--bg-sidebar);
            backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
            border-bottom: 1px solid var(--border-color);
        }}
        .header-brand {{ display: flex; align-items: center; gap: 12px; min-width: 0; }}
        .header-logo {{ height: 48px; max-width: 144px; object-fit: contain; }}
        .header-logo-icon {{ width: 48px; height: 48px; color: var(--accent); }}
        .header-title {{ font-weight: 700; font-size: 1.125rem; white-space: nowrap; }}
        .header-subtitle {{ font-size: 0.75rem; color: var(--text-secondary); white-space: nowrap; }}
        .header-meta {{ display: flex; align-items: center; gap: 12px; font-size: 0.875rem; color: var(--text-secondary); }}
        .header-meta i {{ width: 16px; height: 16px; }}

        /* ═══════════════════════════════════════════════════════════════
           LAYOUT (Sidebar + Main)
           ═══════════════════════════════════════════════════════════════ */
        .app-layout {{ display: flex; min-height: calc(100vh - var(--header-height)); }}

        /* Sidebar */
        .app-sidebar {{
            position: fixed; top: var(--header-height); left: 0; z-index: 1020;
            width: var(--sidebar-width); height: calc(100vh - var(--header-height));
            background: var(--bg-sidebar);
            backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
            border-right: 1px solid var(--border-color);
            overflow-y: auto; overflow-x: hidden;
            transform: translateX(-100%);
            transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }}
        .app-sidebar.open {{ transform: translateX(0); }}
        @media (min-width: 992px) {{
            .app-sidebar {{ position: sticky; transform: translateX(0); }}
        }}
        .sidebar-backdrop {{
            position: fixed; inset: 0; z-index: 1010;
            background: rgba(0,0,0,0.5);
            opacity: 0; pointer-events: none;
            transition: opacity 0.3s ease;
        }}
        .sidebar-backdrop.active {{ opacity: 1; pointer-events: auto; }}

        .sidebar-nav {{ padding: 12px; }}
        .sidebar-search {{
            width: 100%; padding: 10px 14px; margin-bottom: 12px;
            border-radius: 12px; border: 1px solid var(--border-color);
            background: var(--bg-card); color: var(--text-primary); font-size: 0.8125rem;
            outline: none; transition: border-color 0.2s ease, box-shadow 0.2s ease;
        }}
        .sidebar-search:focus {{ border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-light); }}
        .sidebar-search::placeholder {{ color: var(--text-muted); }}

        .nav-link {{
            display: flex; align-items: center; gap: 10px;
            padding: 8px 14px; border-radius: 10px;
            font-size: 0.8125rem; color: var(--text-secondary);
            border: none; background: transparent; cursor: pointer;
            width: 100%; text-align: left;
            border-left: 2px solid transparent;
            transition: all 0.15s ease;
        }}
        .nav-link:hover {{ background: rgba(255,255,255,0.05); color: var(--text-primary); }}
        .nav-link.active {{
            background: var(--accent-light); color: var(--accent);
            border-left-color: var(--accent);
        }}
        .nav-link i {{ width: 16px; height: 16px; flex-shrink: 0; }}
        .nav-link span {{ overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; }}
        .nav-badge {{
            margin-left: auto; background: var(--accent); color: #fff;
            font-size: 0.6875rem; padding: 2px 8px; border-radius: 4px;
            font-weight: 600;
        }}
        .nav-badge--danger {{
            background: var(--risk-critical) !important; color: #fff;
        }}
        .nav-badge--warning {{
            background: var(--risk-high) !important; color: #fff;
        }}

        /* Sidebar menu icon colors (same icons, colored) */
        .app-sidebar .nav-link i,
        .app-sidebar .nav-link svg {{ transition: color 0.2s ease, stroke 0.2s ease; }}
        .app-sidebar .nav-link svg {{ stroke: currentColor; }}
        .app-sidebar .nav-link.nav-icon-dashboard i, .app-sidebar .nav-link.nav-icon-dashboard svg {{ color: #ff6b00; }}
        .app-sidebar .nav-link.nav-icon-risks i, .app-sidebar .nav-link.nav-icon-risks svg {{ color: #ef4444; }}
        .app-sidebar .nav-link.nav-icon-critical_risks i, .app-sidebar .nav-link.nav-icon-critical_risks svg {{ color: #dc2626; }}
        .app-sidebar .nav-link.nav-icon-high_risks i, .app-sidebar .nav-link.nav-icon-high_risks svg {{ color: #f59e0b; }}
        .app-sidebar .nav-link.nav-icon-privileged_accounts i, .app-sidebar .nav-link.nav-icon-privileged_accounts svg {{ color: #8b5cf6; }}
        .app-sidebar .nav-link.nav-icon-delegation_risks i, .app-sidebar .nav-link.nav-icon-delegation_risks svg {{ color: #06b6d4; }}
        .app-sidebar .nav-link.nav-icon-password_issues i, .app-sidebar .nav-link.nav-icon-password_issues svg {{ color: #22c55e; }}
        .app-sidebar .nav-link.nav-icon-users i, .app-sidebar .nav-link.nav-icon-users svg {{ color: #3b82f6; }}
        .app-sidebar .nav-link.nav-icon-computers i, .app-sidebar .nav-link.nav-icon-computers svg {{ color: #6366f1; }}
        .app-sidebar .nav-link.nav-icon-groups i, .app-sidebar .nav-link.nav-icon-groups svg {{ color: #ec4899; }}
        .app-sidebar .nav-link.nav-icon-kerberos i, .app-sidebar .nav-link.nav-icon-kerberos svg {{ color: #eab308; }}
        .app-sidebar .nav-link.nav-icon-paths i, .app-sidebar .nav-link.nav-icon-paths svg {{ color: #14b8a6; }}
        .app-sidebar .nav-link.nav-icon-kerberoasting i, .app-sidebar .nav-link.nav-icon-kerberoasting svg {{ color: #f97316; }}
        .app-sidebar .nav-link.nav-icon-service_accounts i, .app-sidebar .nav-link.nav-icon-service_accounts svg {{ color: #64748b; }}
        .app-sidebar .nav-link.nav-icon-gpo_abuse i, .app-sidebar .nav-link.nav-icon-gpo_abuse svg {{ color: #0ea5e9; }}
        .app-sidebar .nav-link.nav-icon-dcsync_risks i, .app-sidebar .nav-link.nav-icon-dcsync_risks svg {{ color: #a855f7; }}
        .app-sidebar .nav-link.nav-icon-password_policy i, .app-sidebar .nav-link.nav-icon-password_policy svg {{ color: #84cc16; }}
        .app-sidebar .nav-link.nav-icon-trust_risks i, .app-sidebar .nav-link.nav-icon-trust_risks svg {{ color: #2dd4bf; }}
        .app-sidebar .nav-link.nav-icon-certificate_risks i, .app-sidebar .nav-link.nav-icon-certificate_risks svg {{ color: #facc15; }}
        .app-sidebar .nav-link.nav-icon-gpp_risks i, .app-sidebar .nav-link.nav-icon-gpp_risks svg {{ color: #fb923c; }}
        .app-sidebar .nav-link.nav-icon-laps_risks i, .app-sidebar .nav-link.nav-icon-laps_risks svg {{ color: #4ade80; }}
        .app-sidebar .nav-link.nav-icon-vulnerabilities i, .app-sidebar .nav-link.nav-icon-vulnerabilities svg {{ color: #f43f5e; }}
        .app-sidebar .nav-link.nav-icon-legacy_os i, .app-sidebar .nav-link.nav-icon-legacy_os svg {{ color: #94a3b8; }}
        .app-sidebar .nav-link.nav-icon-acl_security i, .app-sidebar .nav-link.nav-icon-acl_security svg {{ color: #f43f5e; }}
        .app-sidebar .nav-link.nav-icon-compliance i, .app-sidebar .nav-link.nav-icon-compliance svg {{ color: #10b981; }}
        .app-sidebar .nav-link.nav-icon-risk_management i, .app-sidebar .nav-link.nav-icon-risk_management svg {{ color: #06b6d4; }}
        .app-sidebar .nav-link.nav-icon-red_team_playbook i, .app-sidebar .nav-link.nav-icon-red_team_playbook svg {{ color: #ef4444; }}
        .app-sidebar .nav-link.nav-icon-blue_team_checklists i, .app-sidebar .nav-link.nav-icon-blue_team_checklists svg {{ color: #3b82f6; }}
        .app-sidebar .nav-link.nav-icon-misconfig i, .app-sidebar .nav-link.nav-icon-misconfig svg {{ color: #22c55e; }}
        .app-sidebar .nav-link.nav-icon-directory i, .app-sidebar .nav-link.nav-icon-directory svg {{ color: #8b5cf6; }}
        .app-sidebar .nav-link.nav-icon-advanced_analysis i, .app-sidebar .nav-link.nav-icon-advanced_analysis svg {{ color: #e11d48; }}
        .app-sidebar .nav-link.nav-icon-hygiene i, .app-sidebar .nav-link.nav-icon-hygiene svg {{ color: #0d9488; }}
        .app-sidebar .nav-link:hover i, .app-sidebar .nav-link:hover svg {{ opacity: 1; }}
        .app-sidebar .nav-link.active i, .app-sidebar .nav-link.active svg {{ color: var(--accent) !important; }}

        /* Main */
        .app-main {{
            flex: 1; min-width: 0;
            padding: 24px; padding-left: 24px;
        }}
        @media (min-width: 992px) {{
            .app-main {{ padding-left: 24px; }}
        }}
        .main-container {{ max-width: 1600px; margin: 0 auto; }}

        /* ═══════════════════════════════════════════════════════════════
           OVERVIEW CARDS
           ═══════════════════════════════════════════════════════════════ */
        .overview-grid {{
            display: grid; grid-template-columns: repeat(2, 1fr);
            gap: 16px; margin-bottom: 24px;
        }}
        @media (min-width: 992px) {{ .overview-grid {{ grid-template-columns: repeat(4, 1fr); }} }}

        .stat-card {{
            background: var(--bg-card); border: 1px solid var(--border-color);
            border-radius: 14px; padding: 20px 24px;
            display: flex; flex-direction: column; justify-content: space-between;
            min-height: 120px;
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }}
        .stat-card:hover {{
            transform: translateY(-3px);
            box-shadow: 0 16px 32px -12px rgba(255, 107, 0, 0.2);
        }}
        .stat-card-header {{ display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }}
        .stat-card-header i {{ width: 24px; height: 24px; color: var(--accent); }}
        .stat-card-label {{
            font-size: 0.75rem; font-weight: 500; color: var(--text-muted);
            text-transform: uppercase; letter-spacing: 0.05em;
        }}
        .kpi-value {{
            font-size: 3rem !important; font-weight: 800 !important;
            letter-spacing: -0.03em !important; line-height: 1.05 !important;
            text-shadow: 0 2px 16px rgba(0,0,0,0.35) !important;
        }}
        .kpi-suffix {{ font-size: 1rem !important; font-weight: 500 !important; opacity: 0.9 !important; }}

        /* KPI Colors */
        .kpi-green {{ color: #22c55e; }}
        .kpi-yellow {{ color: #eab308; }}
        .kpi-orange {{ color: #ff6b00; }}
        .kpi-red {{ color: #ef4444; }}

        /* ═══════════════════════════════════════════════════════════════
           SEARCH/FILTER BAR
           ═══════════════════════════════════════════════════════════════ */
        .section-toolbar {{
            display: flex; flex-wrap: wrap; gap: 8px; align-items: center;
            margin-bottom: 16px;
        }}
        .section-search-wrap {{
            position: relative; flex: 1; min-width: 200px;
        }}
        .section-search-wrap i {{
            position: absolute; left: 14px; top: 50%; transform: translateY(-50%);
            width: 16px; height: 16px; color: var(--text-muted);
        }}
        .section-search {{
            width: 100%; padding: 10px 16px 10px 40px;
            border-radius: 12px; border: 1px solid var(--border-color);
            background: var(--bg-card); color: var(--text-primary);
            font-size: 0.875rem; outline: none;
            transition: border-color 0.2s, box-shadow 0.2s;
        }}
        .section-search:focus {{ border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-light); }}
        .section-search::placeholder {{ color: var(--text-muted); }}

        .toolbar-btn {{
            display: inline-flex; align-items: center; gap: 8px;
            padding: 10px 16px; border-radius: 12px;
            border: 1px solid var(--border-color);
            background: transparent; color: var(--text-secondary);
            font-size: 0.875rem; cursor: pointer;
            transition: background 0.15s, color 0.15s;
        }}
        .toolbar-btn:hover {{ background: rgba(255,255,255,0.05); color: var(--text-primary); }}
        .toolbar-btn i {{ width: 16px; height: 16px; }}

        /* ═══════════════════════════════════════════════════════════════
           BOOTSTRAP DARK OVERRIDES
           ═══════════════════════════════════════════════════════════════ */
        .card {{
            background: var(--bg-card) !important; border-color: var(--border-color) !important;
            border-radius: 14px !important; color: var(--text-primary) !important;
        }}
        .card-header {{
            background: var(--bg-secondary) !important; border-color: var(--border-color) !important;
            color: var(--text-primary) !important; border-radius: 14px 14px 0 0 !important;
            font-weight: 600;
        }}
        .card-body {{ background: var(--bg-card) !important; color: var(--text-primary) !important; }}

        .table {{ color: var(--text-primary) !important; background: var(--bg-card) !important; }}
        .table thead {{ background: var(--bg-secondary) !important; }}
        .table th {{ background: var(--bg-secondary) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .table td {{ background: var(--bg-card) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .table tbody tr {{ background: var(--bg-card) !important; }}
        .table tbody tr:nth-child(even) {{ background: rgba(22, 27, 34, 0.8) !important; }}
        .table tbody tr:hover {{ background: rgba(255, 107, 0, 0.08) !important; }}
        .table-responsive {{ background: var(--bg-card) !important; border-radius: 12px; }}

        /* Heat Map table overrides */
        .table-danger {{ background: rgba(239, 68, 68, 0.3) !important; color: var(--text-primary) !important; }}
        .table-warning {{ background: rgba(245, 158, 11, 0.25) !important; color: var(--text-primary) !important; }}
        .table-info {{ background: rgba(6, 182, 212, 0.2) !important; color: var(--text-primary) !important; }}
        .table-success {{ background: rgba(34, 197, 94, 0.2) !important; color: var(--text-primary) !important; }}
        .table-light, .table thead.table-light {{ background: var(--bg-secondary) !important; color: var(--text-primary) !important; }}

        /* Risk Heat Map - severity-based (same palette as risk cards) */
        .heat-severity-critical td {{ background: color-mix(in srgb, var(--risk-critical) 35%, var(--bg-card)) !important; color: var(--text-primary) !important; border-color: var(--border-subtle) !important; }}
        .heat-severity-high td {{ background: color-mix(in srgb, var(--risk-high) 35%, var(--bg-card)) !important; color: var(--text-primary) !important; border-color: var(--border-subtle) !important; }}
        .heat-severity-medium td {{ background: color-mix(in srgb, var(--risk-medium) 30%, var(--bg-card)) !important; color: var(--text-primary) !important; border-color: var(--border-subtle) !important; }}
        .heat-severity-low td {{ background: color-mix(in srgb, var(--risk-low) 25%, var(--bg-card)) !important; color: var(--text-primary) !important; border-color: var(--border-subtle) !important; }}
        .heat-severity-critical th {{ background: color-mix(in srgb, var(--risk-critical) 50%, var(--bg-card)) !important; color: #fff !important; font-weight: 600; border-color: var(--border-subtle) !important; }}
        .heat-severity-high th {{ background: color-mix(in srgb, var(--risk-high) 50%, var(--bg-card)) !important; color: #fff !important; font-weight: 600; border-color: var(--border-subtle) !important; }}
        .heat-severity-medium th {{ background: color-mix(in srgb, var(--risk-medium) 45%, var(--bg-card)) !important; color: #1a1a1a !important; font-weight: 600; border-color: var(--border-subtle) !important; }}
        .heat-severity-low th {{ background: color-mix(in srgb, var(--risk-low) 40%, var(--bg-card)) !important; color: #1a1a1a !important; font-weight: 600; border-color: var(--border-subtle) !important; }}

        /* Severity badge colors (used report-wide) */
        .badge-severity-critical, .bg-severity-critical {{ background: var(--risk-critical) !important; color: #fff !important; }}
        .badge-severity-high, .bg-severity-high {{ background: var(--risk-high) !important; color: #fff !important; }}
        .badge-severity-medium, .bg-severity-medium {{ background: var(--risk-medium) !important; color: #1a1a1a !important; }}
        .badge-severity-low, .bg-severity-low {{ background: var(--risk-low) !important; color: #fff !important; }}

        /* Risk Cards */
        .risk-card {{ border-radius: 14px !important; margin-bottom: 12px; border-left: 4px solid; transition: all 0.2s ease; }}
        .risk-card:hover {{ transform: translateY(-2px); box-shadow: 0 8px 24px -8px rgba(0,0,0,0.3); }}
        .risk-critical {{ border-left-color: var(--risk-critical) !important; }}
        .risk-high {{ border-left-color: var(--risk-high) !important; }}
        .risk-medium {{ border-left-color: var(--risk-medium) !important; }}
        .risk-low {{ border-left-color: var(--risk-low) !important; }}
        .risk-card-header {{ padding: 16px 20px 8px; }}
        .risk-card-body {{ padding: 0 20px 16px; }}
        .risk-title {{ font-size: 1rem; font-weight: 600; margin-bottom: 4px; }}
        .risk-meta {{ display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }}
        .risk-object {{ font-size: 0.8125rem; }}

        /* Report accordions: professional, minimal panels (Exploitation Commands, Details, etc.) */
        .report-accordion {{ border: none !important; }}
        .report-accordion .accordion-item {{
            background: transparent !important;
            border: 1px solid var(--border-color) !important;
            border-radius: 8px !important;
            margin-bottom: 8px !important;
            overflow: hidden;
        }}
        .report-accordion .accordion-item:last-child {{ margin-bottom: 0 !important; }}
        .report-accordion .accordion-button {{
            background: var(--bg-card) !important;
            color: var(--text-primary) !important;
            border: none !important;
            border-left: 4px solid rgba(255, 107, 0, 0.45) !important;
            border-radius: 8px !important;
            padding: 12px 16px !important;
            font-size: 0.9375rem !important;
            font-weight: 500 !important;
            box-shadow: none !important;
            transition: background 0.2s ease, border-left-color 0.2s ease;
        }}
        .report-accordion .accordion-button:hover {{
            background: var(--bg-secondary) !important;
            border-left-color: rgba(255, 107, 0, 0.7) !important;
        }}
        .report-accordion .accordion-button:not(.collapsed) {{
            background: var(--bg-secondary) !important;
            color: var(--accent) !important;
            border-left-color: var(--accent) !important;
            box-shadow: none !important;
        }}
        .report-accordion .accordion-button::after {{
            filter: brightness(0.85);
        }}
        .report-accordion .accordion-button i {{
            margin-right: 10px;
            opacity: 0.9;
            font-size: 0.875rem;
        }}
        .report-accordion .accordion-button:not(.collapsed) i {{
            color: var(--accent) !important;
        }}
        .report-accordion .accordion-body {{
            background: var(--bg-card) !important;
            color: var(--text-primary) !important;
            border-top: 1px solid var(--border-color) !important;
            padding: 14px 16px !important;
            font-size: 0.875rem !important;
        }}

        /* Legacy accordion (non-report) fallback */
        .accordion:not(.report-accordion) .accordion-button {{ background: var(--bg-card) !important; color: var(--text-primary) !important; border-color: var(--border-color) !important; }}
        .accordion:not(.report-accordion) .accordion-button:not(.collapsed) {{ background: var(--accent-light) !important; color: var(--accent) !important; }}
        .accordion-body {{ background: var(--bg-card) !important; color: var(--text-primary) !important; border-color: var(--border-color) !important; }}
        .accordion-body.matrix-theme {{
            background: #0a0a0a !important; color: #00ff41 !important;
            border: 1px solid #00ff41 !important;
            font-family: Consolas, Monaco, 'Courier New', monospace !important;
        }}
        .accordion-body.matrix-theme p, .accordion-body.matrix-theme li, .accordion-body.matrix-theme code {{ color: #00ff41 !important; }}
        .accordion-body.matrix-theme strong {{ color: #39ff14 !important; }}
        .accordion-body.matrix-theme .text-muted {{ color: #00cc33 !important; }}
        .accordion-body.matrix-theme pre, .accordion-body.matrix-theme code,
        .matrix-theme pre, .matrix-theme code {{ background: #0a0a0a !important; color: #00ff41 !important; border: 1px solid #00ff41 !important; }}
        .accordion-collapse.show .accordion-body.matrix-theme {{ display: block !important; opacity: 1 !important; visibility: visible !important; }}
        .matrix-theme {{ background: #0a0a0a !important; color: #00ff41 !important; border: 1px solid #00ff41 !important; font-family: Consolas, Monaco, 'Courier New', monospace !important; }}
        .matrix-theme p, .matrix-theme strong, .matrix-theme span {{ color: #00ff41 !important; }}

        /* Badges */
        .badge {{ border-radius: 8px !important; }}
        .badge-severity {{ font-size: 0.6875rem; padding: 4px 8px; font-weight: 600; }}

        /* Affected items */
        .affected-items-container {{ display: flex; flex-wrap: wrap; gap: 6px; max-height: 200px; overflow-y: auto; padding: 4px 0; }}
        .affected-item-chip {{
            display: inline-flex; align-items: center; padding: 4px 10px;
            border-radius: 50rem; border: 1px solid var(--border-color);
            background: var(--bg-secondary); color: var(--text-primary);
            font-size: 0.75rem; font-family: Consolas, Monaco, 'Courier New', monospace;
        }}
        .accordion-body.matrix-theme .affected-item-chip {{ border-color: var(--accent); background: var(--accent-light); color: var(--accent); }}

        /* Forms */
        .form-control, .form-select, input, textarea, select {{ background: var(--bg-card) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .form-control::placeholder, input::placeholder {{ color: var(--text-muted) !important; }}
        .input-group-text {{ background: var(--bg-secondary) !important; border-color: var(--border-color) !important; color: var(--text-secondary) !important; }}

        /* Buttons */
        .btn {{ border-color: var(--border-color) !important; }}
        .btn-outline-secondary {{ background: var(--bg-card) !important; color: var(--text-secondary) !important; }}
        .btn-outline-secondary:hover {{ background: var(--bg-secondary) !important; color: var(--text-primary) !important; }}
        .btn-primary {{ background: var(--accent) !important; border-color: var(--accent) !important; color: white !important; }}
        .btn-primary:hover {{ background: var(--accent-hover) !important; border-color: var(--accent-hover) !important; }}
        .btn-success {{ background: #22c55e !important; border-color: #22c55e !important; color: white !important; }}
        .btn-outline-primary {{ color: var(--accent) !important; border-color: var(--accent) !important; }}
        .btn-outline-primary:hover {{ background: var(--accent) !important; color: white !important; }}

        /* Pagination */
        .page-link {{ background: var(--bg-card) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .page-link:hover {{ background: var(--bg-secondary) !important; color: var(--accent) !important; }}
        .page-item.disabled .page-link {{ background: var(--bg-secondary) !important; color: var(--text-muted) !important; }}

        /* Alerts */
        .alert {{ background: var(--bg-secondary) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .alert-warning {{ background: rgba(245, 158, 11, 0.2) !important; border-color: rgba(245, 158, 11, 0.5) !important; }}
        .alert-danger {{ background: rgba(239, 68, 68, 0.2) !important; border-color: rgba(239, 68, 68, 0.5) !important; }}
        .alert-info {{ background: rgba(6, 182, 212, 0.2) !important; border-color: rgba(6, 182, 212, 0.5) !important; }}
        .alert-success {{ background: rgba(34, 197, 94, 0.2) !important; border-color: rgba(34, 197, 94, 0.5) !important; }}

        /* Misc dark overrides */
        .bg-light, .bg-white {{ background: var(--bg-secondary) !important; color: var(--text-primary) !important; }}
        .text-muted {{ color: var(--text-muted) !important; }}
        .text-dark {{ color: var(--text-primary) !important; }}
        .border {{ border-color: var(--border-color) !important; }}
        .breadcrumb {{ background: transparent !important; }}
        .breadcrumb-item a {{ color: var(--accent) !important; text-decoration: none; }}
        .breadcrumb-item.active {{ color: var(--text-secondary) !important; }}
        .list-group {{ background: var(--bg-card) !important; }}
        .list-group-item {{ background: var(--bg-card) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .modal-content {{ background: var(--bg-card) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}
        .modal-header {{ background: var(--bg-secondary) !important; border-color: var(--border-color) !important; }}
        .modal-body {{ background: var(--bg-card) !important; }}
        pre, code {{ background: var(--bg-secondary) !important; color: var(--text-secondary) !important; border-radius: 8px !important; }}
        .report-stat-box, .col .text-center.p-3 {{ background: var(--bg-secondary) !important; border-color: var(--border-color) !important; color: var(--text-primary) !important; }}

        .card-header.bg-warning {{ background: rgba(245, 158, 11, 0.3) !important; color: var(--text-primary) !important; }}
        .card-header.bg-info {{ background: rgba(6, 182, 212, 0.35) !important; color: var(--text-primary) !important; }}
        .card-header.bg-danger {{ background: rgba(239, 68, 68, 0.35) !important; color: var(--text-primary) !important; }}
        .card-header.bg-primary {{ background: rgba(255, 107, 0, 0.35) !important; color: var(--text-primary) !important; }}
        .card-header.bg-secondary {{ background: var(--bg-secondary) !important; color: var(--text-primary) !important; }}
        .card-header.bg-success {{ background: rgba(34, 197, 94, 0.35) !important; color: var(--text-primary) !important; }}
        .card-header.bg-opacity-10 {{ background-color: var(--bg-secondary) !important; }}

        .search-filter-bar {{ background: var(--bg-card); border: 1px solid var(--border-color); padding: 16px; border-radius: 14px; margin-bottom: 16px; }}

        /* ═══════════════════════════════════════════════════════════════
           SCROLL TO TOP
           ═══════════════════════════════════════════════════════════════ */
        #scroll-top {{
            position: fixed; bottom: 24px; right: 24px; z-index: 1050;
            width: 48px; height: 48px; border-radius: 50%;
            background: var(--accent) !important; color: white !important;
            border: none; display: flex; align-items: center; justify-content: center;
            box-shadow: 0 4px 16px rgba(255, 107, 0, 0.4);
            opacity: 0; pointer-events: none;
            transition: all 0.3s ease; cursor: pointer;
        }}
        #scroll-top.visible {{ opacity: 1; pointer-events: auto; }}
        #scroll-top:hover {{ transform: scale(1.1); }}
        #scroll-top i {{ width: 20px; height: 20px; }}

        /* ═══════════════════════════════════════════════════════════════
           FOOTER
           ═══════════════════════════════════════════════════════════════ */
        .app-footer {{
            border-top: 1px solid var(--border-color);
            padding: 24px; margin-top: 32px;
            background: var(--bg-secondary);
            text-align: center; font-size: 0.8125rem; color: var(--text-muted);
        }}
        .app-footer a {{ color: var(--accent); text-decoration: none; }}
        .app-footer a:hover {{ text-decoration: underline; }}

        /* ═══════════════════════════════════════════════════════════════
           TOAST NOTIFICATION
           ═══════════════════════════════════════════════════════════════ */
        .ak-toast {{
            position: fixed; bottom: 80px; right: 24px; z-index: 2000;
            padding: 12px 24px; border-radius: 12px;
            background: var(--bg-card); border: 1px solid var(--accent);
            color: var(--text-primary); font-size: 0.875rem;
            box-shadow: 0 8px 32px rgba(0,0,0,0.4);
            opacity: 0; transform: translateY(20px);
            transition: all 0.3s ease; pointer-events: none;
        }}
        .ak-toast.show {{ opacity: 1; transform: translateY(0); pointer-events: auto; }}

        /* ═══════════════════════════════════════════════════════════════
           ANIMATIONS
           ═══════════════════════════════════════════════════════════════ */
        @keyframes fadeInUp {{
            from {{ opacity: 0; transform: translateY(20px); }}
            to {{ opacity: 1; transform: translateY(0); }}
        }}
        .tab-pane.show {{ animation: fadeInUp 0.25s ease-out; }}

        /* ═══════════════════════════════════════════════════════════════
           PRINT STYLES
           ═══════════════════════════════════════════════════════════════ */
        @media print {{
            :root {{
                --bg-primary: #ffffff; --bg-secondary: #f8f9fa; --bg-card: #ffffff;
                --text-primary: #1a1a1a; --text-secondary: #4a4a4a; --text-muted: #6b6b6b;
                --border-color: #dee2e6; --accent: #d35400;
            }}
            body {{ background: #fff !important; color: #000 !important; font-size: 10pt; }}
            .app-header, .app-sidebar, .sidebar-backdrop,
            #scroll-top, #sidebar-toggle, .section-toolbar,
            .toolbar-btn, .btn, .nav-link {{ display: none !important; }}
            .app-main {{ padding: 0 !important; }}
            .main-container {{ max-width: none !important; }}
            .overview-grid {{ display: grid !important; grid-template-columns: repeat(4, 1fr) !important; }}
            .stat-card, .card {{ box-shadow: none !important; border: 1px solid #ddd !important; break-inside: avoid; }}
            .risk-card {{ break-inside: avoid; page-break-inside: avoid; }}
            .tab-pane {{ display: block !important; opacity: 1 !important; margin-bottom: 2cm; }}
            .tab-content > .tab-pane {{ display: block !important; }}
            .accordion-collapse {{ display: block !important; }}
            a {{ color: #000 !important; text-decoration: none !important; }}
            .badge {{ border: 1px solid #999 !important; }}
            canvas {{ max-width: 100% !important; max-height: 300px !important; }}
            @page {{ margin: 1.5cm; }}
        }}
    </style>
</head>
<body>
    <a href="#main-content" class="skip-link">Skip to main content</a>

    <!-- Header -->
    <header class="app-header" role="banner">
        <div class="header-brand">
            {logo_img}
            <div>
                <div class="header-title">AtilKurt</div>
                <div class="header-subtitle">Active Directory Security Report</div>
            </div>
        </div>
        <div class="header-meta">
            <span class="d-none d-sm-flex align-items-center gap-2">
                <i data-lucide="calendar"></i>
                {report_date}
            </span>
            <button id="sidebar-toggle" class="d-lg-none toolbar-btn" aria-label="Toggle sidebar">
                <i data-lucide="menu"></i>
            </button>
        </div>
    </header>

    <!-- Layout -->
    <div class="app-layout">
        <!-- Sidebar -->
        <aside id="sidebar" class="app-sidebar" role="navigation" aria-label="Report sections">
            <nav class="sidebar-nav" role="tablist">
                <input type="search" id="global-search" class="sidebar-search"
                       placeholder="Search sections..." aria-label="Search report sections" />
                {nav_items}
            </nav>
        </aside>
        <div id="sidebar-backdrop" class="sidebar-backdrop" aria-hidden="true"></div>

        <!-- Main Content -->
        <main id="main-content" class="app-main" role="main">
            <div class="main-container">
                <div id="overview-cards" class="overview-grid">
                    {overview_cards}
                </div>
                <div class="section-toolbar">
                    <div class="section-search-wrap">
                        <i data-lucide="search"></i>
                        <input type="search" id="section-search" class="section-search"
                               placeholder="Search in current section..." aria-label="Search in section" />
                    </div>
                    <button id="copy-section" class="toolbar-btn" title="Copy section to clipboard">
                        <i data-lucide="copy"></i> Copy
                    </button>
                    <button id="print-report" class="toolbar-btn" title="Print report">
                        <i data-lucide="printer"></i> Print
                    </button>
                </div>
                <div class="tab-content-wrapper">
                    {tab_content}
                </div>
            </div>
        </main>
    </div>

    <!-- Footer -->
    <footer class="app-footer" role="contentinfo">
        <strong>Developer</strong>: {html_module.escape(developer_info.get('name', ''))} &middot;
        <a href="mailto:{html_module.escape(developer_info.get('email', ''))}">{html_module.escape(developer_info.get('email', ''))}</a> &middot;
        <a href="{html_module.escape(developer_info.get('linkedin', '#'))}" target="_blank" rel="noopener">LinkedIn</a> &middot;
        <a href="{html_module.escape(developer_info.get('github', '#'))}" target="_blank" rel="noopener">GitHub</a>
        <div style="margin-top: 8px; font-size: 0.75rem;">
            Generated by <strong>AtilKurt</strong> on {report_date}
        </div>
    </footer>

    <!-- Scroll to top -->
    <button id="scroll-top" aria-label="Scroll to top"><i data-lucide="arrow-up"></i></button>

    <!-- Toast notification -->
    <div id="ak-toast" class="ak-toast"></div>

    <!-- ═══════════════════════════════════════════════════════════════
         JAVASCRIPT — All interactive functionality
         ═══════════════════════════════════════════════════════════════ -->
    <script>
    (function() {{
        'use strict';

        // ── Utilities ──────────────────────────────────────────────
        function showToast(msg, duration) {{
            duration = duration || 2000;
            var t = document.getElementById('ak-toast');
            if (!t) return;
            t.textContent = msg;
            t.classList.add('show');
            clearTimeout(t._tid);
            t._tid = setTimeout(function() {{ t.classList.remove('show'); }}, duration);
        }}

        function debounce(fn, ms) {{
            var timer;
            return function() {{
                var ctx = this, args = arguments;
                clearTimeout(timer);
                timer = setTimeout(function() {{ fn.apply(ctx, args); }}, ms);
            }};
        }}

        // ── Tab Navigation ─────────────────────────────────────────
        function showTab(paneId) {{
            var pane = document.getElementById(paneId);
            if (!pane) return;
            document.querySelectorAll('.tab-pane').forEach(function(p) {{ p.classList.remove('show', 'active'); }});
            document.querySelectorAll('#sidebar .nav-link').forEach(function(b) {{ b.classList.remove('active'); }});
            pane.classList.add('show', 'active');
            var sidebarBtn = document.querySelector('#sidebar [data-tab-target="#' + paneId + '"]');
            if (sidebarBtn) sidebarBtn.classList.add('active');
            var cardsEl = document.getElementById('overview-cards');
            if (cardsEl) cardsEl.style.display = (paneId === 'dashboard') ? '' : 'none';
            document.getElementById('main-content').scrollIntoView({{ behavior: 'smooth', block: 'start' }});
            if (paneId === 'password-issues' && typeof window.updatePasswordIssuesFullTable === 'function') window.updatePasswordIssuesFullTable();
        }}
        window.navigateToTab = function(tabId) {{
            var paneId = tabId.replace(/-tab$/, '');
            showTab(paneId);
            // Close sidebar on mobile
            var sb = document.getElementById('sidebar');
            var bd = document.getElementById('sidebar-backdrop');
            if (sb) sb.classList.remove('open');
            if (bd) bd.classList.remove('active');
        }};
        window.showTab = showTab;

        // ── Sidebar toggle ─────────────────────────────────────────
        document.getElementById('sidebar-toggle')?.addEventListener('click', function() {{
            var sb = document.getElementById('sidebar');
            var bd = document.getElementById('sidebar-backdrop');
            sb?.classList.toggle('open');
            bd?.classList.toggle('active');
        }});
        document.getElementById('sidebar-backdrop')?.addEventListener('click', function() {{
            document.getElementById('sidebar')?.classList.remove('open');
            this.classList.remove('active');
        }});

        // ── Sidebar tab click handlers ─────────────────────────────
        document.querySelectorAll('#sidebar [data-tab-target]').forEach(function(btn) {{
            btn.addEventListener('click', function(e) {{
                e.preventDefault();
                var targetId = this.getAttribute('data-tab-target');
                if (targetId) showTab(targetId.replace('#', ''));
            }});
        }});

        // ── Scroll to top ──────────────────────────────────────────
        window.addEventListener('scroll', function() {{
            var btn = document.getElementById('scroll-top');
            if (!btn) return;
            if (window.pageYOffset > 300) btn.classList.add('visible');
            else btn.classList.remove('visible');
        }});
        document.getElementById('scroll-top')?.addEventListener('click', function() {{
            window.scrollTo({{ top: 0, behavior: 'smooth' }});
        }});

        // ── Copy section ───────────────────────────────────────────
        document.getElementById('copy-section')?.addEventListener('click', function() {{
            var pane = document.querySelector('.tab-pane.show.active');
            if (pane && navigator.clipboard) {{
                navigator.clipboard.writeText(pane.innerText).then(function() {{
                    showToast('Section copied to clipboard!');
                }});
            }}
        }});

        // ── Print button ───────────────────────────────────────────
        document.getElementById('print-report')?.addEventListener('click', function() {{
            window.print();
        }});

        // ── Section search (in current tab) ──────────────────────────
        document.getElementById('section-search')?.addEventListener('input', debounce(function() {{
            var q = this.value.toLowerCase();
            var pane = document.querySelector('.tab-pane.show.active');
            if (!pane) return;
            pane.querySelectorAll('.risk-card, .card, tbody tr').forEach(function(el) {{
                el.style.display = (el.textContent.toLowerCase().indexOf(q) !== -1 || !q) ? '' : 'none';
            }});
        }}, 200));

        // ── Sidebar search ────────────────────────────────────────
        document.getElementById('global-search')?.addEventListener('input', debounce(function() {{
            var q = this.value.toLowerCase();
            document.querySelectorAll('#sidebar .nav-link').forEach(function(link) {{
                link.style.display = (link.textContent.toLowerCase().indexOf(q) !== -1 || !q) ? '' : 'none';
            }});
        }}, 150));

        // ── Risk list filter/search/sort/export ──────────────────────
        function initRiskListControls() {{
            document.querySelectorAll('[id^="search_"][id$="_export"]').forEach(function(btn) {{
                btn.addEventListener('click', function() {{
                    var baseId = this.id.replace('_export', '');
                    var container = document.getElementById('risks_container_' + baseId.replace('search_', ''));
                    exportContainerToCsv(container, baseId.replace('search_', ''));
                }});
            }});

            document.querySelectorAll('.search-filter-bar input[type="text"], .search-filter-bar select').forEach(function(el) {{
                el.addEventListener('input', debounce(function() {{
                    filterRiskList(this);
                }}, 200));
                el.addEventListener('change', function() {{
                    filterRiskList(this);
                }});
            }});
        }}

        function filterRiskList(trigger) {{
            var bar = trigger.closest('.search-filter-bar');
            if (!bar) return;
            var searchInput = bar.querySelector('input[type="text"]');
            var severitySelect = bar.querySelector('select[id$="_severity"]');
            var typeSelect = bar.querySelector('select[id$="_type"]');
            var sortSelect = bar.querySelector('select[id$="_sort"]');
            var resultsEl = bar.querySelector('small[id$="_results"]');

            var q = searchInput ? searchInput.value.toLowerCase() : '';
            var sev = severitySelect ? severitySelect.value : '';
            var typ = typeSelect ? typeSelect.value : '';
            var sort = sortSelect ? sortSelect.value : 'score-desc';

            var container = bar.nextElementSibling;
            while (container && !container.querySelector('.risk-cards-container')) {{
                container = container.querySelector('.risk-cards-container') || container.nextElementSibling;
            }}
            if (!container) return;
            var cardsContainer = container.querySelector('.risk-cards-container') || container;
            var cards = Array.from(cardsContainer.querySelectorAll('.risk-card'));
            var visible = 0;

            cards.forEach(function(card) {{
                var text = card.textContent.toLowerCase();
                var cardSev = card.getAttribute('data-severity') || '';
                var cardType = card.getAttribute('data-type') || '';
                var matchQ = !q || text.indexOf(q) !== -1;
                var matchSev = !sev || cardSev === sev;
                var matchType = !typ || cardType === typ;
                if (matchQ && matchSev && matchType) {{
                    card.style.display = '';
                    visible++;
                }} else {{
                    card.style.display = 'none';
                }}
            }});

            if (resultsEl) resultsEl.textContent = 'Showing ' + visible + ' of ' + cards.length + ' risks';

            // Sort
            var sortedCards = cards.filter(function(c) {{ return c.style.display !== 'none'; }});
            sortedCards.sort(function(a, b) {{
                if (sort === 'score-desc') return parseFloat(b.getAttribute('data-score') || 0) - parseFloat(a.getAttribute('data-score') || 0);
                if (sort === 'score-asc') return parseFloat(a.getAttribute('data-score') || 0) - parseFloat(b.getAttribute('data-score') || 0);
                if (sort === 'title-asc') return (a.querySelector('.risk-title')?.textContent || '').localeCompare(b.querySelector('.risk-title')?.textContent || '');
                if (sort === 'title-desc') return (b.querySelector('.risk-title')?.textContent || '').localeCompare(a.querySelector('.risk-title')?.textContent || '');
                return 0;
            }});
            sortedCards.forEach(function(card) {{ cardsContainer.appendChild(card); }});
        }}

        // ── CSV Export Functions ────────────────────────────────────
        function exportContainerToCsv(container, name) {{
            if (!container) {{ showToast('No data to export'); return; }}
            var cards = container.querySelectorAll('.risk-card');
            if (!cards.length) {{ showToast('No visible risks to export'); return; }}
            var rows = [['Title', 'Severity', 'Score', 'Affected', 'Description']];
            cards.forEach(function(card) {{
                if (card.style.display === 'none') return;
                var title = (card.querySelector('.risk-title') || card.querySelector('.card-title'))?.textContent?.trim() || '';
                var severity = card.getAttribute('data-severity') || '';
                var score = card.getAttribute('data-score') || '';
                var affected = card.querySelector('.risk-object')?.textContent?.replace('Affected:', '').trim() || '';
                var desc = card.querySelector('.card-text')?.textContent?.trim() || '';
                rows.push([title, severity, score, affected, desc.substring(0, 300)]);
            }});
            downloadCsv(rows, (name || 'risks') + '_export.csv');
        }}

        function downloadCsv(rows, filename) {{
            var csv = rows.map(function(row) {{
                return row.map(function(cell) {{
                    var v = String(cell).replace(/"/g, '""');
                    return '"' + v + '"';
                }}).join(',');
            }}).join('\\n');
            var blob = new Blob(['\\uFEFF' + csv], {{ type: 'text/csv;charset=utf-8;' }});
            var link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = filename;
            link.click();
            URL.revokeObjectURL(link.href);
            showToast('CSV exported: ' + filename);
        }}

        // Global export functions
        window.exportRiskSectionToCsv = function(containerId, name) {{
            var container = document.getElementById(containerId);
            exportContainerToCsv(container, name);
        }};
        window.exportSingleRiskToCsv = function(btn) {{
            var card = btn.closest('.risk-card');
            if (!card) return;
            var title = (card.querySelector('.risk-title') || card.querySelector('.card-title'))?.textContent?.trim() || '';
            var severity = card.getAttribute('data-severity') || '';
            var score = card.getAttribute('data-score') || '';
            var affected = card.querySelector('.risk-object')?.textContent?.replace('Affected:', '').trim() || '';
            var desc = card.querySelector('.card-text')?.textContent?.trim() || '';
            var rows = [['Title', 'Severity', 'Score', 'Affected', 'Description'],
                        [title, severity, score, affected, desc.substring(0, 500)]];
            downloadCsv(rows, 'risk_' + title.substring(0, 30).replace(/[^a-zA-Z0-9]/g, '_') + '.csv');
        }};

        // ── Kerberoasting / Misconfig search ───────────────────────
        window.filterKerberoasting = function() {{
            var q = (document.getElementById('kerberoastingSearch')?.value || '').toLowerCase();
            document.querySelectorAll('#kerberoastingContainer .risk-card').forEach(function(card) {{
                card.style.display = (!q || card.textContent.toLowerCase().indexOf(q) !== -1) ? '' : 'none';
            }});
        }};
        window.clearKerberoastingSearch = function() {{
            var el = document.getElementById('kerberoastingSearch');
            if (el) {{ el.value = ''; filterKerberoasting(); }}
        }};
        window.filterMisconfig = function() {{
            var q = (document.getElementById('misconfigSearch')?.value || '').toLowerCase();
            document.querySelectorAll('#misconfigContainer .risk-card').forEach(function(card) {{
                card.style.display = (!q || card.textContent.toLowerCase().indexOf(q) !== -1) ? '' : 'none';
            }});
        }};
        window.clearMisconfigSearch = function() {{
            var el = document.getElementById('misconfigSearch');
            if (el) {{ el.value = ''; filterMisconfig(); }}
        }};

        // ── Initialize ────────────────────────────────────────────
        lucide.createIcons();
        initRiskListControls();

    }})();
    </script>
</body>
</html>'''


def _build_overview_cards(kpis):
    """Build 4 overview metric cards from CISO KPIs."""
    cards = []
    kpi_keys = ['overall_score', 'critical_risks', 'high_risks', 'privileged_accounts']
    labels = {'overall_score': 'Security Score', 'critical_risks': 'Critical Risks', 'high_risks': 'High Risks', 'privileged_accounts': 'Privileged Accounts'}
    icons = {'overall_score': 'gauge', 'critical_risks': 'alert-octagon', 'high_risks': 'alert-triangle', 'privileged_accounts': 'user-cog'}
    color_map = {'green': 'kpi-green', 'yellow': 'kpi-yellow', 'orange': 'kpi-orange', 'red': 'kpi-red'}

    for key in kpi_keys:
        kpi = kpis.get(key, {'value': 0, 'label': labels.get(key, key), 'color': 'green'})
        val = kpi['value']
        display = f'{val:.1f}' if key == 'overall_score' and isinstance(val, (int, float)) else str(val)
        color_cls = color_map.get(kpi.get('color', 'green'), 'kpi-green')
        suffix = '<span class="kpi-suffix">/100</span>' if key == 'overall_score' else ''
        cards.append(f'''
                <div class="stat-card">
                    <div class="stat-card-header">
                        <i data-lucide="{icons.get(key, 'activity')}"></i>
                        <span class="stat-card-label">{labels.get(key, kpi.get('label', key))}</span>
                    </div>
                    <p class="kpi-value {color_cls}">{display}{suffix}</p>
                </div>''')
    return ''.join(cards)


def _build_nav_items(stats):
    """Build sidebar navigation items - maps to Bootstrap tab triggers."""
    nav_config = [
        ('dashboard-tab', 'dashboard', 'Dashboard', 'layout-dashboard', None, None),
        ('risks-tab', 'risks', 'All Risks', 'alert-triangle', str(stats.get('total_risks', 0)), None),
        ('critical-risks-tab', 'critical-risks', 'Critical Risks', 'alert-octagon', str(stats.get('critical_count', 0)), 'danger'),
        ('high-risks-tab', 'high-risks', 'High Risks', 'alert-circle', str(stats.get('high_count', 0)), 'warning'),
        ('privileged-accounts-tab', 'privileged-accounts', 'Privileged Accounts', 'user-cog', None, None),
        ('delegation-risks-tab', 'delegation-risks', 'Delegation Risks', 'network', None, None),
        ('password-issues-tab', 'password-issues', 'Password Issues', 'key', None, None),
        ('users-tab', 'users', 'Users', 'users', None, None),
        ('computers-tab', 'computers', 'Computers', 'server', None, None),
        ('groups-tab', 'groups', 'Groups', 'users-round', None, None),
        ('kerberos-tab', 'kerberos', 'Kerberos', 'key', None, None),
        ('paths-tab', 'paths', 'Paths', 'git-branch', None, None),
        ('kerberoasting-tab', 'kerberoasting', 'Kerberoasting', 'flame', None, None),
        ('service-accounts-tab', 'service-accounts', 'Services', 'settings', None, None),
        ('gpo-abuse-tab', 'gpo-abuse', 'GPO', 'shield', None, None),
        ('dcsync-risks-tab', 'dcsync-risks', 'DCSync', 'refresh-cw', None, None),
        ('password-policy-tab', 'password-policy', 'Password Policy', 'lock', None, None),
        ('trust-risks-tab', 'trust-risks', 'Trusts', 'handshake', None, None),
        ('certificate-risks-tab', 'certificate-risks', 'Certificates', 'award', None, None),
        ('gpp-risks-tab', 'gpp-risks', 'GPP Passwords', 'file-text', None, None),
        ('laps-risks-tab', 'laps-risks', 'LAPS', 'shield-check', None, None),
        ('vulnerabilities-tab', 'vulnerabilities', 'Vulnerabilities', 'bug', None, None),
        ('advanced-analysis-tab', 'advanced-analysis', 'Advanced Analysis', 'microscope', None, None),
        ('hygiene-tab', 'hygiene', 'AD Hygiene', 'brush', None, None),
        ('legacy-os-tab', 'legacy-os', 'Legacy OS', 'monitor', None, None),
        ('acl-security-tab', 'acl-security', 'ACL Security', 'shield-alert', None, None),
        ('compliance-tab', 'compliance', 'Compliance', 'clipboard-check', None, None),
        ('risk-management-tab', 'risk-management', 'Risk Management', 'trending-up', None, None),
        ('red-team-playbook-tab', 'red-team-playbook', 'Red Team Playbook', 'target', None, None),
        ('blue-team-checklists-tab', 'blue-team-checklists', 'Blue Team Checklists', 'shield-check', None, None),
        ('misconfig-tab', 'misconfig', 'Recommendations', 'check-circle', None, None),
        ('directory-tab', 'directory', 'Directory', 'book-open', None, None),
    ]
    items = []
    for i, (btn_id, pane_id, label, icon, badge, badge_class) in enumerate(nav_config):
        if badge is not None:
            cls = f' nav-badge--{badge_class}' if badge_class else ''
            badge_el = f'<span class="nav-badge{cls}">{badge}</span>'
        else:
            badge_el = ''
        active_cls = ' active' if i == 0 else ''
        icon_cls = f' nav-icon-{pane_id.replace("-", "_")}'
        items.append(f'''
                <button type="button" role="tab" data-tab-target="#{pane_id}" id="{btn_id}"
                        class="nav-link{active_cls}{icon_cls}" aria-selected="{'true' if i == 0 else 'false'}">
                    <i data-lucide="{icon}"></i>
                    <span>{label}</span>
                    {badge_el}
                </button>''')
    return ''.join(items)
